### PR TITLE
Sqlite

### PR DESCRIPTION
**Pull request by fire**
Changes for sqlite.

Open questions:

- [x] 1. datetime as a string needs testing (assumes utc.)
- [x] 2. branching on runtime detection of sqlite is ugly
- [x] 3. Extract node js updates
- [x] 4. `timestamps(type: :string)` is sus

### CODE REVIEW

**Comment by fire** [comment]
As per the forum https://sqlite.org/forum/info/61d9c6640c6b5ac4, ecto uses a fake datatype TEXT_DATETIME to represent as string. Trying to use a real type like TEXT.

**Review by lyuma — COMMENTED** [review]
Datetime being stored as a string sounds bad. usually this is a source of bugs.
if it was being done this way, that is probably a mistake, or it was using a datetime object which internally might use a different representation
regardless, I think it might make sense to use an int64 unix timestamp in UTC (seconds or milliseconds)
I don't know what is conventional here. probably doesn't matter too much as long as it's an integer and in UTC (not local time zone)

package-lock.json changed. that should probably be a separate commit

Instead of if / else for the whole table definition, we should only wrap the things that changed
for example, if the determination is that :string is the appropriate equivalent of :uuid in sqlite, we should make a variable called uuid_type and set it to :string or :uuid depending on database type, possibly in a global location or superclass
and then the migrations can just reference uuid_type which will be the same type

For datetime, I would be in favor of changing it to integer unix timestamp in UTC, instead of using datetime/string types.

I haven't reviewed the rest of the changes. there were many lines changed.

I think we should collapse the migrations. it's very difficult to follow the alter table and so on
I hope the change you made was automated. otherwise it looks like a lot of work

**Comment by fire** [comment]
1. I am using the standard https://hexdocs.pm/ecto_sqlite3/Ecto.Adapters.SQLite3.html#module-limitations-and-caveats conversion to UTC + TEXT.
2. package-lock.json is now a separate commit
3. if / else for the whole table definition is removed
4. I was assisted by Github pilot but I still made the changes.

**Comment by fire** [comment]
I pushed the datatype changes up stream https://github.com/elixir-sqlite/ecto_sqlite3/pull/97

**Comment by fire** [comment]
Sqlite says it has support for three standard time representations. https://sqlite.org/datatype3.html

> Date and Time Datatype
>
> SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in [Date And Time Functions](https://sqlite.org/lang_datefunc.html) of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values:
>
>    TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS").
>    REAL as Julian day numbers, the number of days since noon in Greenwich on November 24, 4714 B.C. according to the proleptic Gregorian calendar.
>    INTEGER as Unix Time, the number of seconds since 1970-01-01 00:00:00 UTC. 
>
> Applications can choose to store dates and times in any of these formats and freely convert between formats using the built-in [date and time functions](https://sqlite.org/lang_datefunc.html).

**Comment by fire** [comment]
The blocker was folding the postgresql migration so we can recode to sqlite or other.

**Comment by fire** [comment]
# Closing SQLite with FoundationDB PR

## Reason

SQLite on FoundationDB may not be the best fit for V-Sekai due to potential compatibility issues and limited data types.

## Alternative: YugabyteDB

YugabyteDB is being trialed for its scalability, compatibility, and data type support.

## Next Steps

1. Assess YugabyteDB compatibility.
2. Set up a single-node instance.
3. Migrate data.
4. Update application code.
5. Test stability and performance.

## Conclusion

Closing the SQLite with FoundationDB PR allows the team to focus on implementing YugabyteDB as a more suitable database solution.

**Pull request closed without merging**
