### PR TITLE
Discord sign-in support

### PR DESCRIPTION
**Pull request by SaracenOne**
Add support for sign-in with Discord via PowAssent, as well as the ability to link and unlink existing accounts. Other login providers should be easy to add support for now too. Addresses this issue #30

### CODE REVIEW

**Comment by fire** [comment]
Leaving a note saying Discord signin is in limbo due to lack of consensus.

**Comment by lyuma** [comment]
Well it seems fire is forcing my hand at replying to this PR. Why do you no longer support this? I support adding discord login, so did you, saracen and benbot.

Admittedly I don't really understand enough of this code to give it a proper review. Pow is like a black box to me, and it's hard for me to tell from reading the code how the unique username code relates to discord sign in.

I'm a little worried about making the username depend on the discord username (e.g. Lyuma + numbers)

Anyway... two approvals seems fine in my book to merge it. But I'll leave it up to your judgement.

**Comment by fire** [comment]
I’m stating it as an observation because it’s not merged and we are prioritizing relationship management which is double friending and not sso. I don’t know why we aren’t merging.

On Sep 19, 2022, at 9:26 PM, lyuma ***@***.***> wrote:

﻿
Well it seems fire is forcing my hand at replying to this PR. Why do you no longer support this? I support adding discord login, so did you, saracen and benbot.

Admittedly I don't really understand enough of this code to give it a proper review. Pow is like a black box to me, and it's hard for me to tell from reading the code how the unique username code relates to discord sign in.

I'm a little worried about making the username depend on the discord username (e.g. Lyuma + numbers)

Anyway... two approvals seems fine in my book to merge it. But I'll leave it up to your judgement.

**Comment by fire** [comment]
Superseded by: https://github.com/V-Sekai/uro/commit/d9679031f4526c93a72284b2a122d994350a788c

**Pull request closed without merging**
